services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_HOST=pg_db
      - DB_USER=citizix_user
      - DB_PASSWORD=S3cret


  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
    hostname: pg_db



