# Generated by Django 5.0.6 on 2024-07-17 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_parcel_update_datetime'),
        ('post_machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='locker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_machine.locker'),
        ),
    ]
